### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by YamatoSecurity**
Still WIP but I'm uploading now so you can translate what I have done so far. Feel free to update the Japanese readme and push changes.

### CODE REVIEW

**Comment by fukusuket** [comment]
Japanese README has been updated. I will check and update it again when the version updated!

**Review by fukusuket — COMMENTED** [review]
Japanese README has been updated. I will check and update it again when the version updated!

**Comment by YamatoSecurity** [comment]
@fukusuket Sorry since we don't have much time before the conference, can you approve this so we can merge it?
After that, please create a separate PR for the JP translations. After that, I will add the `registry` event info and then `wmi` if that is possible.

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀

**Pull request merged**
