### PR TITLE
feat: add supported modifier

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
Added supported modifier.

## Test
There was no change in numbers. (There still seems to be no rule for the modifier we added)
```
% diff -q -r converted_sigma_rules_new converted_sigma_rules_old
%
```

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
Thanks!
I think it is `cased`, not `case`. Can you also add a `contains|cased`, `startswith|cased` and `endswith|cased` to the table?

**Comment by YamatoSecurity** [comment]
@fukusuket Sorry, `Can you also add a contains|cased, startswith|cased and endswith|cased to the table?` -> needs to be fixed in the hayabusa-rules repository script.

**Comment by fukusuket** [comment]
@YamatoSecurity 

https://github.com/Yamato-Security/sigma-to-hayabusa-converter/pull/30#pullrequestreview-2462838303
Sorry! I made a mistake. I fixed it!

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks! LGTM!

**Pull request merged**
