### PR TITLE
feat: add conversion process for `wmi_event`

### LINKED ISSUE #12: Investigate conversion of `wmi_event` events
We may be able to convert `wmi_event` categories to handle built-in WMI logs.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #12
- Specification: https://github.com/Yamato-Security/sigma-to-hayabusa-converter/issues/12#issuecomment-2333441655

@YamatoSecurity 
I created it with the above specifications. What do you think?
If we find additional EventIDs that can be converted, we can add processing in the future.

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
## original rule
```yml
title: WMI Event Subscription
id: 0f06a3a5-6a09-413f-8743-e6cf35561297
status: test
description: Detects creation of WMI event subscription persistence method
references:
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-19-wmievent-wmieventfilter-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-20-wmievent-wmieventconsumer-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-21-wmievent-wmieventconsumertofilter-activity-detected
author: Tom Ueltschi (@c_APT_ure)
date: 2019-01-12
modified: 2021-11-27
tags:
    - attack.persistence
    - attack.t1546.003
logsource:
    product: windows
    category: wmi_event
detection:
    selection:
        EventID:
            - 19
            - 20
            - 21
    condition: selection
falsepositives:
    - Exclude legitimate (vetted) use of WMI event subscription in your network
level: medium
```

## converted rule
```yml
title: WMI Event Subscription
id: 3318e98f-7614-2bef-f5b2-78af7cbba518
related:
    - id: 0f06a3a5-6a09-413f-8743-e6cf35561297
      type: derived
status: test
description: Detects creation of WMI event subscription persistence method
references:
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-19-wmievent-wmieventfilter-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-20-wmievent-wmieventconsumer-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-21-wmievent-wmieventconsumertofilter-activity-detected
author: Tom Ueltschi (@c_APT_ure)
date: 2019-01-12
modified: 2021-11-27
tags:
    - attack.persistence
    - attack.t1546.003
    - sysmon
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID: 5861
        Channel: Microsoft-Windows-WMI-Activity/Operational
    condition: wmi_event
falsepositives:
    - Exclude legitimate (vetted) use of WMI event subscription in your network
level: medium
ruletype: Sigma
```

**Comment by fukusuket** [comment]
## original rule
```yml
title: Suspicious Encoded Scripts in a WMI Consumer
id: 83844185-1c5b-45bc-bcf3-b5bf3084ca5b
status: test
description: Detects suspicious encoded payloads in WMI Event Consumers
references:
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems)
date: 2021-09-01
modified: 2022-10-09
tags:
    - attack.execution
    - attack.t1047
    - attack.persistence
    - attack.t1546.003
logsource:
    product: windows
    category: wmi_event
detection:
    selection_destination:
        Destination|base64offset|contains:
            - 'WriteProcessMemory'
            - 'This program cannot be run in DOS mode'
            - 'This program must be run under Win32'
    condition: selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Unknown
level: high
```

## converted rule
```yml
title: Suspicious Encoded Scripts in a WMI Consumer
id: f4e538d8-94a9-8ecc-779e-e03aa85aedb4
related:
    - id: 83844185-1c5b-45bc-bcf3-b5bf3084ca5b
      type: derived
status: test
description: Detects suspicious encoded payloads in WMI Event Consumers
references:
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems)
date: 2021-09-01
modified: 2022-10-09
tags:
    - attack.execution
    - attack.t1047
    - attack.persistence
    - attack.t1546.003
    - sysmon
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID: 5861
        Channel: Microsoft-Windows-WMI-Activity/Operational
    selection_destination:
        UserDataPossibleCause|base64offset|contains:
            - WriteProcessMemory
            - This program cannot be run in DOS mode
            - This program must be run under Win32
    condition: wmi_event and selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Unknown
level: high
ruletype: Sigma
```

**Comment by fukusuket** [comment]
## original rule
```yml
title: Suspicious Scripting in a WMI Consumer
id: fe21810c-2a8c-478f-8dd3-5a287fb2a0e0
status: test
description: Detects suspicious commands that are related to scripting/powershell in WMI Event Consumers
references:
    - https://in.security/an-intro-into-abusing-and-identifying-wmi-event-subscriptions-for-persistence/
    - https://github.com/Neo23x0/signature-base/blob/615bf1f6bac3c1bdc417025c40c073e6c2771a76/yara/gen_susp_lnk_files.yar#L19
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro
date: 2019-04-15
modified: 2023-09-09
tags:
    - attack.execution
    - attack.t1059.005
logsource:
    product: windows
    category: wmi_event
detection:
    selection_destination:
        - Destination|contains|all:
              - 'new-object'
              - 'net.webclient'
              - '.downloadstring'
        - Destination|contains|all:
              - 'new-object'
              - 'net.webclient'
              - '.downloadfile'
        - Destination|contains:
              - ' iex('
              - ' -nop '
              - ' -noprofile '
              - ' -decode '
              - ' -enc '
              - 'WScript.Shell'
              - 'System.Security.Cryptography.FromBase64Transform'
    condition: selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Legitimate administrative scripts
level: high
```
## converted rule
```yml
title: Suspicious Scripting in a WMI Consumer
id: 93786e05-1808-f3b1-9841-7fee02fd7247
related:
    - id: fe21810c-2a8c-478f-8dd3-5a287fb2a0e0
      type: derived
status: test
description: Detects suspicious commands that are related to scripting/powershell in WMI Event Consumers
references:
    - https://in.security/an-intro-into-abusing-and-identifying-wmi-event-subscriptions-for-persistence/
    - https://github.com/Neo23x0/signature-base/blob/615bf1f6bac3c1bdc417025c40c073e6c2771a76/yara/gen_susp_lnk_files.yar#L19
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro
date: 2019-04-15
modified: 2023-09-09
tags:
    - attack.execution
    - attack.t1059.005
    - sysmon
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID: 5861
        Channel: Microsoft-Windows-WMI-Activity/Operational
    selection_destination:
        - UserDataPossibleCause|contains|all:
              - new-object
              - net.webclient
              - .downloadstring
        - UserDataPossibleCause|contains|all:
              - new-object
              - net.webclient
              - .downloadfile
        - UserDataPossibleCause|contains:
              - ' iex('
              - ' -nop '
              - ' -noprofile '
              - ' -decode '
              - ' -enc '
              - WScript.Shell
              - System.Security.Cryptography.FromBase64Transform
    condition: wmi_event and selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Legitimate administrative scripts
level: high
ruletype: Sigma
```

**Comment by fukusuket** [comment]
## Test
### Rule diff
No unnecessary differences.
```
% diff -qr converted_sigma_rules_new converted_sigma_rules_old                            
Only in converted_sigma_rules_new/builtin: wmi_event
Files converted_sigma_rules_new/sysmon/wmi_event/sysmon_wmi_event_subscription.yml and converted_sigma_rules_old/sysmon/wmi_event/sysmon_wmi_event_subscription.yml differ
```
### Hayabusa parse error
hayabusa is not getting rule parsing errors.
```
./hayabusa-2.17.0-mac-aarch64 csv-timeline -r converted_sigma_rules_new -w -d ../hayabusa-sample-evtx -o timeline.csv -C -q
Start time: 2024/09/14 08:57

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.

Excluded rules: 20

Deprecated rules: 216 (5.23%) (Disabled)
Experimental rules: 507 (12.27%)
Stable rules: 114 (2.76%)
Test rules: 3,510 (84.97%)
Unsupported rules: 45 (1.09%) (Disabled)

Sigma rules: 4,131
Total detection rules: 4,131

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 571
Detection rules enabled after channel filter: 4,081
```

### Hayabusa result diff
No difference in results.
```
% ./hayabusa-2.17.0-mac-aarch64 csv-timeline -r converted_sigma_rules_new -w -d ../hayabusa-sample-evtx -o new.csv -C -q
% ./hayabusa-2.17.0-mac-aarch64 csv-timeline -r converted_sigma_rules_old -w -d ../hayabusa-sample-evtx -o old.csv -C -q
% diff old.csv new.csv
%
```

I found the following bug during testing .. 😓 will fix it in another pull request.
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter/issues/21

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks! For now, we can just do field name changes for the field names that are being used. Later on, I will try to look more into this.
I ran an action with this branch but it seems to add back the `sysmon` tags to the `builtin` rules. Can you check this?

**Comment by YamatoSecurity** [comment]
@fukusuket Also, I think the converted `builtin` rules are good, but for some reason, the event ID selection was deleted from one of the sysmon rules. I think we need to leave the sysmon channel field and event ID fields for the sysmon rules with a category of `wmi_event`.
wmi_event

Note: I think there is a problem in this rule in that it should not be necessary to specify the Event IDs in this rule since it should already be included in the category portion. I will create an issue in the upstream sigma repo to ask about this. For now, although the fields get duplicated, I think since it's a problem with the original rule, we should just keep the duplicate fields.

**Comment by fukusuket** [comment]
@YamatoSecurity Thank you so much for checking!
>I ran an action with this branch but it seems to add back the sysmon tags to the builtin rules. Can you check this?

Yes!, because this branch does not include pull requests https://github.com/Yamato-Security/sigma-to-hayabusa-converter/pull/22 !

>  I will create an issue in the upstream sigma repo to ask about this. For now, although the fields get duplicated, I think since it's a problem with the original rule, we should just keep the duplicate fields.

I agree! I intentionally implemented a process to remove the above block, but I will eliminate this process. (As an issue in the Sigma repository, not addressed in the converter script) 💪

**Comment by fukusuket** [comment]
Close this pull request and create a new pull request with the above specifications!

**Pull request closed without merging**
