### PR TITLE
fix: derived UUID and Ignore placefolder and Consolidate config

### LINKED ISSUE #11: Consolidate and renaming of config files
@fukusuket Could I ask you to rename and consolidate the following files:

* `sysmon.yaml` -> `sysmon-category-mapping.yaml` file rename
* `windows-services.yaml` -> `services-mapping.yaml` file rename
* `windows-audit.yaml` -> `builtin-category-mapping.yaml` file rename
* Merge `windows-antivirus.yaml` info into `builtin-category-mapping.yaml` file 

I think this will be easier to understand/manage.

### LINKED ISSUE #13: Derived rule IDs may be invalid
I have only checked a few rules, but it seems that the derived IDs may be invalid.

Now:
Built-in rule:
```
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694
```

Sysmon rule:
```
title: 7Zip Compressing Dump Files
id: e02e1c15-b64d-0c08-3771-5948dfb17ed7
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
    - id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
      type: derived
```

What it should be:
Built-in rule:
```
title: 7Zip Compressing Dump Files
id: e02e1c15-b64d-0c08-3771-5948dfb17ed7
related:
    - id: 93586827-5f54-fc91-0b2f-338fd5365694
      type: derived
```

Sysmon rule:
```
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694 
```

### LINKED ISSUE #14: Ignore "placeholder" rules
Currently, Hayabusa does not support `|expand` and `%placeholder%` placeholders so there is no need to convert them. I think we can do this easily by just not including the `rules-placeholder` folder in the Sigma repository. @fukusuket

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #11 
- Closed #13 
- Closed #14

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
Sorry... I ran actions and once it was merged, I am running actions again with the module before the modification.
(The latest of the current haybausa_rule was run on the main branch before this PR change)

This PR
https://github.com/Yamato-Security/hayabusa-rules/pull/689/files

main
https://github.com/Yamato-Security/hayabusa-rules/pull/690/files

**Comment by fukusuket** [comment]
### Ignore "placeholder" rules #14
I confirmed that the place-holder folder has been deleted as follows
https://github.com/Yamato-Security/hayabusa-rules/pull/689/files#diff-3a1522609bb1327e5ccbadc122eb3e96ef6d8d928cf20d9cd5fd8f21cc8c2087

**Comment by fukusuket** [comment]
### Consolidate and renaming of config files #11
I confirmed that there are no differences in the `sigma/builtin/windefend folder`.
https://github.com/Yamato-Security/hayabusa-rules/pull/689/files

**Comment by fukusuket** [comment]
### Derived rule IDs may be invalid #13
I confirmed that the conversion is in accordance with https://github.com/Yamato-Security/sigma-to-hayabusa-converter/issues/13#issuecomment-2263263182 specifications.

https://github.com/SigmaHQ/sigma/blob/c5e352c270c47597ef28776d8c8d235d49d80c45/rules/windows/process_creation/proc_creation_win_7zip_exfil_dmp_files.yml#L1-L6
```yaml
title: 7Zip Compressing Dump Files
id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
status: test
```
https://github.com/Yamato-Security/hayabusa-rules/pull/689/files#
sigma/builtin/process_creation/proc_creation_win_7zip_exfil_dmp_files.yml
```yaml
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
    - id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
      type: derived
status: test
```

**Comment by fukusuket** [comment]
### hayabusa-sample-evtx
There is no parse error.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/10201425845/job/28223222200#step:9:4777

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! Thanks so much!

**Pull request merged**
