### PR TITLE
feat: add conversion process for `wmi_event`

### LINKED ISSUE #12: Investigate conversion of `wmi_event` events
We may be able to convert `wmi_event` categories to handle built-in WMI logs.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed #12
- Specification: 
   - https://github.com/Yamato-Security/sigma-to-hayabusa-converter/issues/12#issuecomment-2333441655
   - https://github.com/Yamato-Security/sigma-to-hayabusa-converter/pull/20#issuecomment-2354776084

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
## Test
### Rule diff
No unnecessary differences.
```
 % diff -rq converted_sigma_rules_new converted_sigma_rules_old
Only in converted_sigma_rules_new/builtin: wmi_event
```

### Hayabusa parse error
hayabusa is not getting rule parsing errors.
```
% ./hayabusa-2.17.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -q -w -D -n -u -
r converted_sigma_rules_new -C -o new.csv
Start time: 2024/09/17 21:32

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.

Excluded rules: 20

Deprecated rules: 216 (4.92%)
Experimental rules: 507 (11.54%)
Stable rules: 114 (2.60%)
Test rules: 3,510 (79.92%)
Unsupported rules: 45 (1.02%)

Sigma rules: 4,392
Total detection rules: 4,392

Creating the channel filter. Please wait.

Evtx files loaded after channel filter: 571
Detection rules enabled after channel filter: 4,340

Output profile: standard
```

### Hayabusa result diff
No difference in results.
```
% ./hayabusa-2.17.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -q -w -D -n -u -r converted_sigma_rules_new -C -o new.csv
% ./hayabusa-2.17.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -q -w -D -n -u -r converted_sigma_rules_old -C -o old.csv
% diff old.csv new.csv
% 
```

**Comment by fukusuket** [comment]
### converted rule(builtin)
```yml
title: Suspicious Scripting in a WMI Consumer
id: 93786e05-1808-f3b1-9841-7fee02fd7247
related:
    - id: fe21810c-2a8c-478f-8dd3-5a287fb2a0e0
      type: derived
status: test
description: Detects suspicious commands that are related to scripting/powershell in WMI Event Consumers
references:
    - https://in.security/an-intro-into-abusing-and-identifying-wmi-event-subscriptions-for-persistence/
    - https://github.com/Neo23x0/signature-base/blob/615bf1f6bac3c1bdc417025c40c073e6c2771a76/yara/gen_susp_lnk_files.yar#L19
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro
date: 2019-04-15
modified: 2023-09-09
tags:
    - attack.execution
    - attack.t1059.005
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID: 5861
        Channel: Microsoft-Windows-WMI-Activity/Operational
    selection_destination:
        - UserDataPossibleCause|contains|all:
              - new-object
              - net.webclient
              - .downloadstring
        - UserDataPossibleCause|contains|all:
              - new-object
              - net.webclient
              - .downloadfile
        - UserDataPossibleCause|contains:
              - ' iex('
              - ' -nop '
              - ' -noprofile '
              - ' -decode '
              - ' -enc '
              - WScript.Shell
              - System.Security.Cryptography.FromBase64Transform
    condition: wmi_event and selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Legitimate administrative scripts
level: high
ruletype: Sigma
```

### converted rule(sysmon)
```yml
title: Suspicious Scripting in a WMI Consumer
id: 56bbb635-99ed-e718-f300-582130579092
related:
    - id: fe21810c-2a8c-478f-8dd3-5a287fb2a0e0
      type: derived
status: test
description: Detects suspicious commands that are related to scripting/powershell in WMI Event Consumers
references:
    - https://in.security/an-intro-into-abusing-and-identifying-wmi-event-subscriptions-for-persistence/
    - https://github.com/Neo23x0/signature-base/blob/615bf1f6bac3c1bdc417025c40c073e6c2771a76/yara/gen_susp_lnk_files.yar#L19
    - https://github.com/RiccardoAncarani/LiquidSnake
author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro
date: 2019-04-15
modified: 2023-09-09
tags:
    - attack.execution
    - attack.t1059.005
    - sysmon
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID:
            - 19
            - 20
            - 21
        Channel: Microsoft-Windows-Sysmon/Operational
    selection_destination:
        - Destination|contains|all:
              - new-object
              - net.webclient
              - .downloadstring
        - Destination|contains|all:
              - new-object
              - net.webclient
              - .downloadfile
        - Destination|contains:
              - ' iex('
              - ' -nop '
              - ' -noprofile '
              - ' -decode '
              - ' -enc '
              - WScript.Shell
              - System.Security.Cryptography.FromBase64Transform
    condition: wmi_event and selection_destination
fields:
    - User
    - Operation
falsepositives:
    - Legitimate administrative scripts
level: high
ruletype: Sigma
```

**Comment by fukusuket** [comment]
Case https://github.com/Yamato-Security/sigma-to-hayabusa-converter/pull/20#issuecomment-2354776084
```yml
title: WMI Event Subscription
id: 3799c466-edf8-bc53-6747-8908ab796483
related:
    - id: 0f06a3a5-6a09-413f-8743-e6cf35561297
      type: derived
status: test
description: Detects creation of WMI event subscription persistence method
references:
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-19-wmievent-wmieventfilter-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-20-wmievent-wmieventconsumer-activity-detected
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon#event-id-21-wmievent-wmieventconsumertofilter-activity-detected
author: Tom Ueltschi (@c_APT_ure)
date: 2019-01-12
modified: 2021-11-27
tags:
    - attack.persistence
    - attack.t1546.003
    - sysmon
logsource:
    product: windows
    category: wmi_event
detection:
    wmi_event:
        EventID:
            - 19
            - 20
            - 21
        Channel: Microsoft-Windows-Sysmon/Operational
    selection:
        EventID:
            - 19
            - 20
            - 21
    condition: wmi_event and selection
falsepositives:
    - Exclude legitimate (vetted) use of WMI event subscription in your network
level: medium
ruletype: Sigma
```

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Thanks so much! LGTM!
I updated the changelog and added the UUID to ignore the `title: WMI Event Subscription
id: 3799c466-edf8-bc53-6747-8908ab796483` rule as it is not needed.

**Pull request merged**
